stages:
  - test
  - build
  - deploy

test:btsoot:
  stage: test
  script:
    - python3.6 -m py_compile btsoot.py

test:copy:
  stage: test
  script:
    - cd copy
    - scan-build make test
    - cd ..

build:copy:
  stage: build
  script:
    - cd copy
    - make
    - cd ..
  artifacts:
    paths:
      - ./copy/copy

deploy:dpkg:
  stage: deploy
  script:
    - print "hello"
