stages:
  - test
  - build
  - package

btsoot_test:
  stage: test
  script:
    - python3.6 -m py_compile btsoot.py

copy_test:
  stage: test
  script:
    - cd copy
    - scan-build make test
    - cd ..

copy_build:
  stage: build
  script:
    - cd copy
    - make
    - cd ..
  artifacts:
    paths:
      - ./copy/copy

dpkg:
  stage: package
  script:
    - ls
    - echo $PWD
