stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - make production -j 16

test:
  stage: test
  script:
    - scan-build make production -j 16
  when: 
    - manual

web_testing:
  stage: package
  environment: testing
  script:
    - make production -j 16
    - cp btsoot.x86_64 /home/paul/nas/btsoot/testing/btsoot-$CI_PIPELINE_ID-$CI_ENVIRONMENT_NAME

web_stable:
  stage: package
  environment: stable
  script:
    - make production -j 16
    - cp ./btsoot.x86_64 /home/paul/nas/btsoot/stable/btsoot-$CI_COMMIT_TAG-$CI_ENVIRONMENT_NAME
  only:
    - tags
    
web_rolling:
  stage: package
  environment: rolling
  script:
    - make production -j 16
    - cp ./btsoot.x86_64 /home/paul/nas/stable/btsoot-$CI_PIPELINE_ID-$CI_ENVIRONMENT_NAME
  only:
    - master
