stages:
  - test
  - build
  - deploy

btsoot:
  stage: test
  script:
    - python3.6 -m py_compile btsoot.py

copy:
  stage: test
  script:
    - cd copy
    - scan-build make test
    - cd ..

copy:
  stage: build
  script:
    - cd copy
    - make
    - cd ..
  artifacts:
    paths:
      - ./copy/copy

dpkg:
  stage: deploy
  script:
    - ls
    - echo $PWD
